# Site Settings
lang: 'en'
title: Loving Angel
theme: Loving Angel Theme 
author: 'AEDesign'
description: 'This Theme was build only for practice purposes by AEDesign'
keywords: 'Jekyll (Blog-aware, Static Site Generator) & Github, Github Pages & Website Design & PSD to HTML & Responsive Design & HTML, HTML5 &  CSS2, CSS3 & Js, Jquery & Sass/ SCSS & Adobe Photoshop & CMS for Static Site ( siteleaf, forestry, prose )'

# Site Info
email: aedesignbohol@gmail.com
address: ''
phone: '+63 956 812 8297'

social:
- { name: 'twitter', link: '/'}
- { name: 'facebook', link: 'https://www.facebook.com/aedesignbohol/'}