#Site Settings
lang: 'en'
author: AEDesign-Bohol
title: ''
subtitle: ''
description: ''
keywords: ''

#Site Info
email: 'lovingangel@gmail.com'
website: ''
addresss: ''
phone: 'soon'
mobile: 
 smart: '+63 923 913 2582'
 globe: '+63 859 961 8325'
